- name: Add docker apt signing key
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: 0644
    force: true

- name: Add docker repository to apt sources
  become: true
  ansible.builtin.apt_repository:
    state: present
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu noble stable
    filename: docker

- name: Install docker packages
  become: true
  ansible.builtin.apt:
    state: present
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Create docker directory
  become: true
  ansible.builtin.file:
    state: directory
    path: /opt/docker
