name: Configure

on:
  workflow_dispatch:

jobs:
  ansible_testing:
    name: Ansible (testing)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Write inventory
        shell: bash
        run: echo "${{ secrets.VM_PUBLIC_IP_ADDRESS }}" > testing

      - name: Run playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          PUBLIC_IP_ADDRESS: ${{ secrets.VM_PUBLIC_IP_ADDRESS }}
        run: ansible-playbook -i testing candidate-test-vms.yml -u azureuser --extra-vars "ansible_password=${{ secrets.VM_PASSWORD }}"
